package projet_demineur;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author tciab
 */
public class NewJFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NewJFrame.class.getName());

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRoot = new javax.swing.JPanel();
        pnlTop = new javax.swing.JPanel();
        lbllignes = new javax.swing.JLabel();
        spLignes = new javax.swing.JSpinner();
        lblcolonnes = new javax.swing.JLabel();
        spcolonnes = new javax.swing.JSpinner();
        lblBombes = new javax.swing.JLabel();
        spBombes = new javax.swing.JSpinner();
        lblKits = new javax.swing.JLabel();
        spKits = new javax.swing.JSpinner();
        btnNouvellePartie = new javax.swing.JButton();
        lblVies = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlRoot.setLayout(new java.awt.BorderLayout());
        getContentPane().add(pnlRoot, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 58, -1, -1));

        lbllignes.setText("Lignes");
        pnlTop.add(lbllignes);
        pnlTop.add(spLignes);

        lblcolonnes.setText("colonnes");
        pnlTop.add(lblcolonnes);
        pnlTop.add(spcolonnes);

        lblBombes.setText("Bombes");
        pnlTop.add(lblBombes);
        pnlTop.add(spBombes);

        lblKits.setText("Kits");
        pnlTop.add(lblKits);
        pnlTop.add(spKits);

        btnNouvellePartie.setText("Nouvelle Partie");
        pnlTop.add(btnNouvellePartie);

        lblVies.setText("Vies : 3");
        pnlTop.add(lblVies);

        getContentPane().add(pnlTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new NewJFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNouvellePartie;
    private javax.swing.JLabel lblBombes;
    private javax.swing.JLabel lblKits;
    private javax.swing.JLabel lblVies;
    private javax.swing.JLabel lblcolonnes;
    private javax.swing.JLabel lbllignes;
    private javax.swing.JPanel pnlRoot;
    private javax.swing.JPanel pnlTop;
    private javax.swing.JSpinner spBombes;
    private javax.swing.JSpinner spKits;
    private javax.swing.JSpinner spLignes;
    private javax.swing.JSpinner spcolonnes;
    // End of variables declaration//GEN-END:variables
}
